# Numpy

numpy - numeric python
fast calculation

## conventional method
l = [1,2,3,4,5,6,7,8,9]
sum = 0 
for i in l:
    sum = sum + i
print(sum)

#fast method using numpy
import numpy as np
l = np.array([1,2,3,4,5,6,7,8,9])
print(np.sum(l))

In [3]:
import numpy as np
l = [1, 2.4, 'hello', True] #List
a = np.array(l)    # Array


## Creating a numpy array

In [13]:
list1 = [[1,2,3],[4,5,6],[7,8,9]]
array1 = np.array(list1)
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
#  Method2
array2 = np.zeros((2,3))
array2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
#  Method3
array3 = np.ones((2,3))
array3


array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
#Method4
array4 = np.full((3,3), 99)
array4

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

In [11]:
# Method 5
array5 = np.arange(0, 10, 2)
array5

array([0, 2, 4, 6, 8])

In [12]:
#Method 6
array6 = np.linspace(0, 1, 5)
array6

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr)
print(arr.shape)
print(arr.dtype)
print(arr.ndim)
print(arr.size)
print(arr.itemsize)
print(arr.data)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
int32
2
9
4


In [ ]:
arr[1:,1:]

array([[5, 6],
       [8, 9]])

In [27]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = np.array([10,20,30,40,50,60,70,80,90])

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a % b)
print(a ** b)
print(a // b)
print(a > b)
print(a < b)
print(a >= b)
print(a <= b)
print(a == b)
print(a != b)

[11 22 33 44 55 66 77 88 99]
[ -9 -18 -27 -36 -45 -54 -63 -72 -81]
[ 10  40  90 160 250 360 490 640 810]
[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
[1 2 3 4 5 6 7 8 9]
[          1     1048576 -1010140999           0  1296002393           0
  1187094929           0  -949019631]
[0 0 0 0 0 0 0 0 0]
[False False False False False False False False False]
[ True  True  True  True  True  True  True  True  True]
[False False False False False False False False False]
[ True  True  True  True  True  True  True  True  True]
[False False False False False False False False False]
[ True  True  True  True  True  True  True  True  True]


In [29]:
arr
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.std(arr))

45
5.0
9
2.581988897471611


In [ ]:
arr = np.array([1,2,4,5,6,7,8,9,10])

print(arr.reshape(9,1))

[[ 1]
 [ 2]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


In [36]:
print(arr[arr >5])

[ 6  7  8  9 10]


In [ ]:
print(arr[[1,3,5]]) # pick elements at index 1, 3, 5

[2 5 7]


In [39]:
print(arr[arr%2 == 0])# print even numbers

[ 2  4  6  8 10]


In [45]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
c = np.array([[1,2],[3,4]])
print(np.dot(a,b))
print(np.transpose(a))
print(np.linalg.inv(c))# Inverse
print(np.linalg.det(c))# Determinant

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004


In [51]:
arr[0] = 100
x = arr.view()
print(x)

y = arr.copy()
print(y)

[100   2   4   5   6   7   8   9  10]
[100   2   4   5   6   7   8   9  10]
